name = "barbearia-workers"
main = "src/index.js"
compatibility_date = "2025-01-01"
compatibility_flags = [ "nodejs_compat" ]

[vars]
NODE_ENV = "production"
EMAIL_PROVIDER = "brevo"
EMAIL_FROM = "Marque’s Barbearia <no-reply@localhost>"
EMAIL_BRAND_NAME = "Marque’s Barbearia"
SUPABASE_URL = "https://zniehugopmvoutxnpgox.supabase.co"

